# Mostly auto-generated by the widget cookiecutter
from __future__ import print_function
from setuptools import setup, find_packages
import os
from os.path import join as pjoin
import pathlib
from distutils import log

from jupyter_packaging import (
    create_cmdclass,
    install_npm,
    ensure_targets,
    combine_commands,
    get_version,
)


here = os.path.dirname(os.path.abspath(__file__))

log.set_verbosity(log.DEBUG)
log.info("setup.py entered")
log.info("$PATH=%s" % os.environ["PATH"])

name = "ipyannotations"

LONG_DESCRIPTION = pathlib.Path("README.md").read_text()

# Get ipyannotations version
version = get_version(pjoin("src", name, "_version.py"))

js_dir = pjoin(here, "src", "js")

# Representative files that should exist after a successful build
jstargets = [
    pjoin(js_dir, "dist", "index.js"),
]

data_files_spec = [
    (
        "share/jupyter/nbextensions/ipyannotations",
        "src/ipyannotations/nbextension",
        "*.*",
    ),
    (
        "share/jupyter/labextensions/ipyannotations",
        "src/ipyannotations/labextension",
        "**",
    ),
    ("share/jupyter/labextensions/ipyannotations", ".", "install.json"),
    ("etc/jupyter/nbconfig/notebook.d", ".", "ipyannotations.json"),
]

cmdclass = create_cmdclass("jsdeps", data_files_spec=data_files_spec)
cmdclass["jsdeps"] = combine_commands(
    install_npm(js_dir, npm=["yarn"], build_cmd="build:prod"),
    ensure_targets(jstargets),
)

setup_args = dict(
    name=name,
    version=version,
    description="Create rich adata annotations in jupyter notebooks.",
    long_description=LONG_DESCRIPTION,
    include_package_data=True,
    package_dir={"": "src/"},
    install_requires=[
        "ipywidgets>=7.6.0",
        "ipycanvas",
        "palettable",
        "Pillow",
        "numpy",
        "requests",
        "dataclasses; python_version == '3.6'",
        "ipyevents",
    ],
    extras_require={
        "test": [
            "pytest",
            "coverage",
            "coveralls",
            "pytest-cov",
            "hypothesis",
            "pytest-check",
            "mypy",
        ],
        "dev": [
            "black",
            "flake8",
            "pre-commit",
            "jupyterlab",
            "rope",
            "docargs",
        ],
        "doc": [
            "sphinx>=2.3",
            "sphinx_rtd_theme",
            "nbsphinx",
            "myst-parser>=0.12.9",
        ],
    },
    packages=find_packages(where="src/"),
    zip_safe=False,
    cmdclass=cmdclass,
    author="Jan Freyberg",
    author_email="jan.freyberg@gmail.com",
    url="https://github.com/janfreyberg/ipyannotations",
    keywords=[
        "ipython",
        "jupyter",
        "widgets",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Framework :: IPython",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Multimedia :: Graphics",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)

setup(**setup_args)
