name: Build

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-3.9-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.9-
            pip-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools codecov jupyter_packaging twine
          npm install -g codecov
      - name: Update version to test version
        if: (github.event_name == 'push' && !startsWith(github.event.ref, 'refs/tags')) || github.event_name == 'pull_request'
        run: |
          python -m pip install testver>=0.3.1
          testver --mode=tuple --varname=version_info ipyannotations/_version.py
      - name: Test the extension
        run: |
          python -m pip install --upgrade --use-feature=in-tree-build ".[test,examples,doc,dev]"
          yarn run lint:check
          yarn run test
      - name: Check docs can be built
        run: |
          sudo apt install -y pandoc
          pushd docs
          make html
          popd
      - name: Test the build process
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to Test PYPI
        if: (github.event_name == 'push' && !startsWith(github.event.ref, 'refs/tags')) || github.event_name == 'pull_request'
        run: |
          twine upload dist/ipyannotations*
        env:
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.test_pypi_secret }}
      - name: Publish to real PYPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          twine upload dist/ipyannotations*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_secret }}
